-- APCAS SCMS Day 1 schema. Run in the Supabase SQL editor before replacing mock repositories.
create extension if not exists "pgcrypto";
create type public.account_status as enum ('ACTIVE','PENDING','DISABLED','REVOKED');
create type public.task_scope as enum ('ORGANIZATION','PERSONAL');
create type public.task_status as enum ('TODO','IN_PROGRESS','COMPLETED','CANCELLED');
create type public.expense_status as enum ('DRAFT','SUBMITTED','APPROVED','REJECTED','VOIDED');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete restrict,
  full_name text not null,
  school_email text not null unique,
  is_access_administrator boolean not null default false,
  created_at timestamptz not null default now()
);
create table public.council_accounts (
  id uuid primary key default gen_random_uuid(), auth_user_id uuid unique references auth.users(id) on delete restrict,
  council_id char(8) not null unique check (council_id ~ '^17[0-9]{6}$'),
  status public.account_status not null default 'PENDING',
  created_by uuid references public.profiles(id), created_at timestamptz not null default now(), disabled_at timestamptz, deleted_at timestamptz
);
create table public.projects (id uuid primary key default gen_random_uuid(), title text not null, description text, status text not null default 'ACTIVE', start_date date, end_date date, created_by uuid references public.profiles(id), deleted_at timestamptz, created_at timestamptz not null default now());
create table public.events (id uuid primary key default gen_random_uuid(), title text not null, description text, starts_at timestamptz not null, ends_at timestamptz not null, location text, priority text, project_id uuid references public.projects(id), deleted_at timestamptz, created_at timestamptz not null default now());
create table public.event_reminders (id uuid primary key default gen_random_uuid(), event_id uuid not null references public.events(id) on delete cascade, remind_at timestamptz not null, channel text not null check (channel in ('IN_APP','EMAIL')), delivered_at timestamptz);
create table public.tasks (id uuid primary key default gen_random_uuid(), title text not null, description text, task_scope public.task_scope not null, status public.task_status not null default 'TODO', priority text not null default 'MEDIUM', due_at timestamptz, owner_user_id uuid references public.profiles(id), project_id uuid references public.projects(id), event_id uuid references public.events(id), meeting_id uuid, budget_id uuid, deleted_at timestamptz, created_at timestamptz not null default now(), check ((task_scope = 'PERSONAL' and owner_user_id is not null) or task_scope = 'ORGANIZATION'));
create table public.task_assignees (task_id uuid references public.tasks(id) on delete cascade, profile_id uuid references public.profiles(id), primary key (task_id, profile_id));
create table public.documents (id uuid primary key default gen_random_uuid(), title text not null, storage_path text not null, status text not null default 'DRAFT', project_id uuid references public.projects(id), event_id uuid references public.events(id), meeting_id uuid, deleted_at timestamptz, created_at timestamptz not null default now());
create table public.document_versions (id uuid primary key default gen_random_uuid(), document_id uuid not null references public.documents(id) on delete restrict, version_number integer not null check (version_number > 0), storage_path text not null, uploaded_by uuid references public.profiles(id), created_at timestamptz not null default now(), unique (document_id, version_number));
create table public.meetings (id uuid primary key default gen_random_uuid(), title text not null, occurs_at timestamptz not null, project_id uuid references public.projects(id), minutes text, deleted_at timestamptz, created_at timestamptz not null default now());
create table public.meeting_agenda_items (id uuid primary key default gen_random_uuid(), meeting_id uuid not null references public.meetings(id) on delete cascade, title text not null, sort_order integer not null default 0);
create table public.meeting_attendees (meeting_id uuid references public.meetings(id) on delete cascade, profile_id uuid references public.profiles(id), primary key (meeting_id, profile_id));
create table public.meeting_minutes (id uuid primary key default gen_random_uuid(), meeting_id uuid not null unique references public.meetings(id) on delete cascade, notes text, decisions text, updated_by uuid references public.profiles(id), updated_at timestamptz not null default now());
create table public.budgets (id uuid primary key default gen_random_uuid(), name text not null, description text not null, project_id uuid references public.projects(id), event_id uuid references public.events(id), allocated_amount numeric(14,2) not null check (allocated_amount >= 0), currency char(3) not null default 'PHP', status text not null default 'DRAFT', deleted_at timestamptz, created_at timestamptz not null default now());
create table public.budget_categories (id uuid primary key default gen_random_uuid(), budget_id uuid not null references public.budgets(id) on delete restrict, name text not null, allocated_amount numeric(14,2) not null check (allocated_amount >= 0), unique (budget_id, name));
create table public.expenses (id uuid primary key default gen_random_uuid(), budget_id uuid not null references public.budgets(id) on delete restrict, category_id uuid not null references public.budget_categories(id), title text not null, description text not null, amount numeric(14,2) not null check (amount >= 0), expense_date date not null, status public.expense_status not null default 'DRAFT', receipt_path text, submitted_by uuid references public.profiles(id), voided_at timestamptz, created_at timestamptz not null default now());
create table public.receipts (id uuid primary key default gen_random_uuid(), expense_id uuid not null references public.expenses(id) on delete restrict, storage_path text not null, original_filename text not null, mime_type text not null, size_bytes bigint not null check (size_bytes >= 0), uploaded_at timestamptz not null default now());
create table public.student_concerns (id uuid primary key default gen_random_uuid(), ticket_number text not null unique, category text not null, description text not null, priority text not null default 'MEDIUM', status text not null default 'OPEN', assigned_to uuid references public.profiles(id), anonymous_submitter boolean not null default false, resolution_notes text, deleted_at timestamptz, created_at timestamptz not null default now());
create table public.concern_comments (id uuid primary key default gen_random_uuid(), concern_id uuid not null references public.student_concerns(id) on delete restrict, author_id uuid references public.profiles(id), body text not null, created_at timestamptz not null default now());
create table public.concern_status_history (id uuid primary key default gen_random_uuid(), concern_id uuid not null references public.student_concerns(id) on delete restrict, old_status text, new_status text not null, changed_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.announcements (id uuid primary key default gen_random_uuid(), title text not null, body text not null, audience text not null, status text not null default 'DRAFT', published_at timestamptz, scheduled_for timestamptz, created_by uuid references public.profiles(id), deleted_at timestamptz, created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, success boolean not null, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), notification_type text not null, title text not null, message text not null, entity_type text, entity_id uuid, read_at timestamptz, delivery_channel text not null default 'IN_APP', delivery_status text not null default 'PENDING', created_at timestamptz not null default now());
create table public.notification_preferences (profile_id uuid primary key references public.profiles(id) on delete cascade, in_app_enabled boolean not null default true, school_email_enabled boolean not null default true, default_reminder_minutes integer not null default 60 check (default_reminder_minutes >= 0));
create table public.approval_requests (id uuid primary key default gen_random_uuid(), entity_type text not null, entity_id uuid not null, status text not null default 'PENDING', requested_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.approval_steps (id uuid primary key default gen_random_uuid(), request_id uuid not null references public.approval_requests(id) on delete cascade, step_order integer not null, approver_id uuid references public.profiles(id), status text not null default 'PENDING', decision_note text, decided_at timestamptz, unique (request_id, step_order));

create index events_starts_at_idx on public.events(starts_at); create index tasks_due_at_idx on public.tasks(due_at); create index expenses_budget_date_idx on public.expenses(budget_id, expense_date); create index audit_actor_time_idx on public.audit_logs(actor_id, created_at desc); create index notifications_user_read_idx on public.notifications(user_id, read_at);

-- The only financially authoritative read model; UI must query this RPC/view rather than sum values client-side.
create view public.budget_live_aggregates as select b.id as budget_id, b.allocated_amount as allocated, coalesce(sum(e.amount) filter (where e.status = 'APPROVED'), 0)::numeric(14,2) as actual_spent, (b.allocated_amount - coalesce(sum(e.amount) filter (where e.status = 'APPROVED'), 0))::numeric(14,2) as remaining, case when b.allocated_amount = 0 then 0 else round((coalesce(sum(e.amount) filter (where e.status = 'APPROVED'), 0) / b.allocated_amount) * 100, 2) end as utilization_percent, count(e.id) filter (where e.status = 'APPROVED') as approved_expense_count from public.budgets b left join public.expenses e on e.budget_id = b.id group by b.id;

alter table public.profiles enable row level security; alter table public.council_accounts enable row level security; alter table public.tasks enable row level security;
create function public.is_president() returns boolean language sql stable security definer set search_path = public as $$ select coalesce((select is_access_administrator from public.profiles where id = auth.uid()), false) $$;
-- Personal-task rule: only President-owned records are readable/mutable by the President. Organization rows remain shared.
create policy "task scoped access" on public.tasks for all using ((task_scope = 'ORGANIZATION') or (task_scope = 'PERSONAL' and public.is_president() and owner_user_id = auth.uid())) with check ((task_scope = 'ORGANIZATION') or (task_scope = 'PERSONAL' and public.is_president() and owner_user_id = auth.uid()));
create policy "president manages accounts" on public.council_accounts for all using (public.is_president()) with check (public.is_president());
-- Add equivalent shared-record policies only after confirming their per-operation authorization in service tests.
