"use client";

import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import interactionPlugin from "@fullcalendar/interaction";
import { Bell, CalendarDots, MapPin, Plus, UsersThree } from "@phosphor-icons/react";
import { Button, Card, Badge } from "@/components/ui";

export function CalendarBoard() { return <div className="space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">Planner and reminders</p><h1 className="mt-1 text-2xl font-black tracking-tight">Council calendar</h1></div><Button><Plus size={16} weight="bold"/> Add event</Button></div><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><Card className="p-4 sm:p-5"><FullCalendar plugins={[dayGridPlugin, interactionPlugin]} initialView="dayGridMonth" initialDate="2026-08-01" headerToolbar={{ left: "prev,next today", center: "title", right: "dayGridMonth,dayGridWeek" }} height="auto" editable selectable events={[{ title: "Nursing Week Planning", start: "2026-08-03", color: "#22a565" }, { title: "Submit Event Proposal", start: "2026-08-07", color: "#ef7d6d" }, { title: "Committee Meeting", start: "2026-08-12", color: "#4b94d0" }, { title: "Meeting with Adviser", start: "2026-08-19", color: "#8b6bd9" }, { title: "Document Submission", start: "2026-08-26", color: "#22a565" }]} /></Card><aside className="space-y-4"><Card className="p-5"><div className="flex items-center justify-between"><CalendarDots size={22} className="text-emerald-700" weight="bold"/><Badge tone="green">Confirmed</Badge></div><h2 className="mt-3 text-sm font-black">Nursing Week Planning</h2><p className="mt-1 text-xs text-slate-500">Mon, Aug 3, 2026 · 8:00–9:30 AM</p><div className="mt-4 space-y-2 border-t border-[#e7efe9] pt-4 text-xs text-slate-600"><p className="flex gap-2"><MapPin size={16} className="text-emerald-600" weight="bold"/>Conference Room A</p><p className="flex gap-2"><UsersThree size={16} className="text-emerald-600" weight="bold"/>6 council attendees</p><p className="flex gap-2"><Bell size={16} className="text-emerald-600" weight="bold"/>Two reminders enabled</p></div></Card><Card className="p-5"><h2 className="text-sm font-black">Connected records</h2><div className="mt-3 space-y-2 text-xs">{["Nursing Week 2026 project", "Finalize program flow task", "Nursing Week budget"].map((item) => <a key={item} href="/projects/nursing-week" className="flex items-center justify-between rounded-lg border border-[#e3ece5] p-2.5 text-[#315340] hover:bg-emerald-50"><span>{item}</span><span>›</span></a>)}</div></Card></aside></div></div>; }
