import { Bell, CalendarDots, CaretRight, CheckCircle, ClockCountdown, CurrencyCircleDollar, FileText, Flag, FolderSimple, Plus, ShieldCheck, WarningCircle } from "@phosphor-icons/react/dist/ssr";
import { Card, Badge, Button, peso } from "@/components/ui";

const metrics = [
  { label: "Organization tasks", value: "12", note: "3 overdue", icon: CheckCircle, tone: "text-emerald-600 bg-emerald-50" },
  { label: "Personal tasks", value: "2", note: "President only", icon: ShieldCheck, tone: "text-violet-600 bg-violet-50" },
  { label: "Active projects", value: "4", note: "2 on track", icon: FolderSimple, tone: "text-sky-600 bg-sky-50" },
  { label: "Documents", value: "18", note: "3 updated", icon: FileText, tone: "text-indigo-600 bg-indigo-50" },
];

export function Dashboard() {
  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end">
      <div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">Tuesday · August 24, 2026</p><h1 className="mt-1 text-2xl font-black tracking-tight text-[#143523]">Good morning, Miguel.</h1><p className="mt-1 text-sm text-slate-500">A clear view of today&apos;s council work and connected records.</p></div>
      <div className="flex gap-2"><Button><Plus size={16} weight="bold" /> Quick action</Button><button aria-label="Open notifications" className="relative rounded-lg border border-[#dce8df] bg-white p-2 text-[#0b4624]"><Bell size={18} weight="bold" /><i className="absolute right-1 top-1 h-1.5 w-1.5 rounded-full bg-rose-500" /></button></div>
    </div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ icon: Icon, ...metric }) => <Card key={metric.label} className="p-4"><div className="flex items-center justify-between"><span className={`rounded-xl p-2 ${metric.tone}`}><Icon size={20} weight="bold" /></span><span className="text-2xl font-black text-[#163c28]">{metric.value}</span></div><p className="mt-3 text-xs font-bold text-[#335443]">{metric.label}</p><p className={`mt-1 text-[11px] ${metric.note.includes("overdue") ? "text-rose-600" : "text-slate-400"}`}>{metric.note}</p></Card>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.25fr_.9fr]">
      <div className="space-y-5"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-[#e7efe9] p-5"><div><h2 className="flex items-center gap-2 text-sm font-black"><CalendarDots size={18} weight="bold" className="text-emerald-600"/> Today&apos;s schedule</h2><p className="mt-1 text-xs text-slate-500">Events connected to calendar records</p></div><a href="/calendar" className="text-xs font-bold text-emerald-700">Open calendar <CaretRight className="inline" size={13} weight="bold" /></a></div><div className="divide-y divide-[#edf3ee]">{[["08:00 AM","Nursing Week Planning","Conference Room A","emerald"],["10:00 AM","Submit Event Proposal","Student Council Office","sky"],["03:00 PM","Committee Meeting","Online · Google Meet","violet"]].map(([time,title,place,color]) => <div key={title} className="flex items-center gap-4 px-5 py-3"><div className="w-16 text-[11px] font-bold text-emerald-700">{time}</div><span className={`h-8 w-1 rounded-full bg-${color}-400`} /><div><p className="text-xs font-bold text-[#244632]">{title}</p><p className="mt-0.5 text-[11px] text-slate-400">{place}</p></div></div>)}</div></Card>
      <Card className="p-5"><div className="flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-sm font-black"><CheckCircle size={18} weight="bold" className="text-emerald-600"/> Your organization tasks</h2><p className="mt-1 text-xs text-slate-500">Shared work only</p></div><a href="/tasks" className="text-xs font-bold text-emerald-700">View all</a></div><div className="mt-4 space-y-3">{[["Finalize program flow","High","Today, 5:00 PM","red"],["Confirm venue request","Medium","Tomorrow","amber"],["Review sponsor proposal","Low","Aug 29","green"]].map(([title,priority,due,tone]) => <div key={title} className="flex gap-3 rounded-xl border border-[#e5eee7] p-3"><span className="mt-0.5 h-4 w-4 rounded border border-emerald-300"/><div className="min-w-0 flex-1"><p className="text-xs font-bold text-[#234732]">{title}</p><p className="mt-1 text-[10px] text-slate-400">{due}</p></div><Badge tone={tone as "red" | "amber" | "green"}>{priority}</Badge></div>)}</div></Card></div>
      <div className="space-y-5"><Card className="bg-gradient-to-br from-[#e9f6ed] via-white to-[#f6fbf7] p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-emerald-700">Live budget aggregate</p><h2 className="mt-1 text-lg font-black">Nursing Week 2026</h2></div><CurrencyCircleDollar size={26} className="text-emerald-700" weight="bold"/></div><div className="mt-5 flex items-center gap-5"><div className="grid h-24 w-24 place-items-center rounded-full" style={{background:"conic-gradient(#0b7a43 61.67%, #dceee2 0)"}}><div className="grid h-17 w-17 place-items-center rounded-full bg-white text-center"><b className="text-sm">61.7%</b><span className="text-[9px] text-slate-400">used</span></div></div><div className="space-y-2 text-xs"><p><span className="text-slate-400">Approved spent</span><br/><b className="text-[#16452a]">{peso(18500)}</b></p><p><span className="text-slate-400">Remaining</span><br/><b className="text-[#16452a]">{peso(11500)}</b></p></div></div><a href="/projects/nursing-week" className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-emerald-700">View project budget <CaretRight size={14} weight="bold" /></a></Card>
      <Card className="p-5"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-black"><ClockCountdown size={18} weight="bold" className="text-amber-600"/> Needs attention</h2><Badge tone="amber">4 items</Badge></div><div className="mt-4 space-y-3">{[{ Icon: WarningCircle, title: "Budget hits 80% threshold", note: "Review Printing allocation", color: "text-amber-500" },{ Icon: Flag, title: "Student concern assigned", note: "Library noise · high priority", color: "text-rose-500" },{ Icon: FileText, title: "Document approval due", note: "Nursing Week proposal v3", color: "text-sky-500" }].map(({ Icon, title, note, color }) => <div key={title} className="flex gap-3"><Icon size={19} className={color} weight="fill"/><div><p className="text-xs font-bold">{title}</p><p className="text-[11px] text-slate-400">{note}</p></div></div>)}</div></Card></div>
    </div>
  </div>;
}
